### ISSUE TITLE
Dynamic Sampling

### ISSUE THREAD

**Issue by mike-zorn** [honeycombio/agentless-integrations-for-aws#7]
The honeyaws package supports [dynamic sampling](https://github.com/honeycombio/honeyaws#sampling) for ELB and ALB logs. This allows us to see all errors which we return to clients which are rare relative to successes. Porting that feature over to this would be really beneficial.

**Comment by JamieDanielson** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
