### ISSUE TITLE
cloudwatch-handler currently errors on START/END/REPORT lines; issue seems to be fixed in publisher. Is this intentional?

### ISSUE THREAD

**Issue by manach** [honeycombio/agentless-integrations-for-aws#94]
Hello! I've been working with the [generic JSON CloudWatch integration](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=honeycomb-cloudwatch-integration&templateURL=https://s3.amazonaws.com/honeycomb-builds/honeycombio/integrations-for-aws/LATEST/templates/cloudwatch-logs-json.yml), which I believe is in the agentless-integrations-for-aws/cloudwatch-handler repo. It currently errors when handling Lambda's START/END/REPORT lines.

I'm filing this as a question because I found a fix in the agentless-integrations-for-aws/publisher repo, so I wasn't sure if this was perhaps an intentional choice. If it's unwanted behavior, the lines below from publisher seem like they would fix the issue. There's also a publisher_test in the publisher folder that covers this behavior:

line 17
```
var lambdaReportLineRegex = regexp.MustCompile(`^(START|END|REPORT) RequestId:.+`)
```

lines 74-79
```
                // Skip default lambda START, END, REPORT log lines to avoid "unable to parse"
		// spam below, which can get expensive
		match := lambdaReportLineRegex.FindString(event.Message)
		if match != "" {
			continue
		}
```

I wanted to add:
1) This is being used in a personal/portfolio project. There's no urgency for this change on my end.
2) I am very grateful for this software and for all the efforts of those involved. It is not my intention for this request to be viewed as antagonism towards any developer responsible for the code. Thank you for all your hard work.
3) I added the suggested fix out of a desire to be helpful. I apologize in advance if it's unwelcome.

**Comment by vreynolds** [comment]
Howdy @manach, that's a totally valid question! From what I can tell, the lambda pattern was added to the publisher because it's only intended to work with Honeycomb-structured JSON events, so those lines are safe to ignore. In case of the CloudWatch handler, it can be used with a JSON or a regex parser. If it's used with a regex parser, I can imagine someone might actually want those lines to turn into events with the request ID.

That being said, it seems reasonable to ignore those lines if we know `parserType == "json"` -- no point in trying to parse them since we know they will fail.

**Comment by manach** [comment]
That makes sense! Hope this was useful. Y'all do great work!

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
